import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { RobotMlGeneratedModule, RobotMlGeneratedSharedModule } from './generated/module.js';
import { RobotMlValidator, registerValidationChecks } from './robot-ml-validator.js';
import { RobotMlAcceptWeaver } from '../semantics/robot-ml-accept-weaver.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RobotMlAddedServices = {
    validation: {
        RobotMlValidator: RobotMlValidator
    }
    visitors: {
        RobotMlAcceptWeaver: RobotMlAcceptWeaver
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RobotMlServices = LangiumServices & RobotMlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RobotMlModule: Module<RobotMlServices, PartialLangiumServices & RobotMlAddedServices> = {
    validation: {
        RobotMlValidator: () => new RobotMlValidator()
    },
    visitors: {
        RobotMlAcceptWeaver: (services) => new RobotMlAcceptWeaver(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRobotMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    RobotMl: RobotMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RobotMlGeneratedSharedModule
    );
    const RobotMl = inject(
        createDefaultModule({ shared }),
        RobotMlGeneratedModule,
        RobotMlModule
    );
    shared.ServiceRegistry.register(RobotMl);
    registerValidationChecks(RobotMl);

    // Forcer l'initialisation du Weaver pour que le visiteur marche
    RobotMl.visitors.RobotMlAcceptWeaver;

    if (!context.connection) {
        // Si on n'est pas dans un contexte LSP, on doit initialiser la configuration manuellement
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, RobotMl };
}
