<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robotML" nsURI="http://www.example.org/robotML" nsPrefix="robotML">
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="funcdecl" upperBound="-1"
        eType="#//FuncDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementlist" lowerBound="1"
        eType="#//StatementList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FuncCall" eSuperTypes="#//Statement #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="funcdecl" eType="#//FuncDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarAssign" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vardecl" eType="#//VarDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecl" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TypeVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vardecl" eType="#//VarDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unit">
    <eLiterals name="cm"/>
    <eLiterals name="mm"/>
    <eLiterals name="none" value="2"/>
    <eLiterals name="deg" value="3"/>
    <eLiterals name="rad" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//TypeVar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//TypeVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Movement" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStructure" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//ControlStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//StatementList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//ControlStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBody" lowerBound="1"
        eType="#//StatementList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" eType="#//StatementList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnarOperation" abstract="true" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolUnaryOperation" eSuperTypes="#//UnarOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BoolUOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumUnaryOperation" eSuperTypes="#//UnarOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NumUOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolBinaryOperation" eSuperTypes="#//BinaryOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BoolBOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumBinaryOperation" eSuperTypes="#//BinaryOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NumBOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperation" abstract="true" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="2"
        upperBound="2" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoolUOp">
    <eLiterals name="NOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumUOp">
    <eLiterals name="MINUS"/>
    <eLiterals name="PLUS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoolBOp">
    <eLiterals name="EQ"/>
    <eLiterals name="NEQ" value="1"/>
    <eLiterals name="LEQ" value="2"/>
    <eLiterals name="GEQ" value="3"/>
    <eLiterals name="LE" value="4"/>
    <eLiterals name="GR" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumBOp">
    <eLiterals name="MINUS"/>
    <eLiterals name="PLUS" value="1"/>
    <eLiterals name="MULTIPLY" value="2"/>
    <eLiterals name="DIVIDE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetSpeed" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="speed" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="Backward"/>
    <eLiterals name="Forward" value="1"/>
    <eLiterals name="Sideleft" value="2"/>
    <eLiterals name="Sideright" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorAccess" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" eType="#//SensorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="Distance"/>
    <eLiterals name="Time" value="1"/>
    <eLiterals name="Battery" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeVar" abstract="true" eSuperTypes="#//Type"/>
</ecore:EPackage>
