/**
 * generated by Xtext 2.40.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final /* Programme */Object programme, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nfuncdecl cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* FuncDecl */Object funcDecl, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ntype cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nstatementlist cannot be resolved"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final Object programme, final IFormattableDocument document) {
    if (programme instanceof XtextResource) {
      _format((XtextResource)programme, document);
      return;
    } else if (programme instanceof EObject) {
      _format((EObject)programme, document);
      return;
    } else if (programme == null) {
      _format((Void)null, document);
      return;
    } else if (programme != null) {
      _format(programme, document);
      return;
    } else if (programme != null) {
      _format(programme, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(programme, document).toString());
    }
  }
}
