/*
 * generated by Xtext 2.40.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgrammeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Programme");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProgrammeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProgrammeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFuncdeclKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cFuncdeclAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cFuncdeclFuncDeclParserRuleCall_3_2_0 = (RuleCall)cFuncdeclAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cFuncdeclAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cFuncdeclFuncDeclParserRuleCall_3_3_1_0 = (RuleCall)cFuncdeclAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Programme returns Programme:
		//    {Programme}
		//    'Programme'
		//    '{'
		//        ('funcdecl' '{' funcdecl+=FuncDecl ( "," funcdecl+=FuncDecl)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Programme}
		//'Programme'
		//'{'
		//    ('funcdecl' '{' funcdecl+=FuncDecl ( "," funcdecl+=FuncDecl)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Programme}
		public Action getProgrammeAction_0() { return cProgrammeAction_0; }
		
		//'Programme'
		public Keyword getProgrammeKeyword_1() { return cProgrammeKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('funcdecl' '{' funcdecl+=FuncDecl ( "," funcdecl+=FuncDecl)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'funcdecl'
		public Keyword getFuncdeclKeyword_3_0() { return cFuncdeclKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//funcdecl+=FuncDecl
		public Assignment getFuncdeclAssignment_3_2() { return cFuncdeclAssignment_3_2; }
		
		//FuncDecl
		public RuleCall getFuncdeclFuncDeclParserRuleCall_3_2_0() { return cFuncdeclFuncDeclParserRuleCall_3_2_0; }
		
		//( "," funcdecl+=FuncDecl)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//funcdecl+=FuncDecl
		public Assignment getFuncdeclAssignment_3_3_1() { return cFuncdeclAssignment_3_3_1; }
		
		//FuncDecl
		public RuleCall getFuncdeclFuncDeclParserRuleCall_3_3_1_0() { return cFuncdeclFuncDeclParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBoolParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNumberParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVoidParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Type returns Type:
		//    Bool | Number | Void;
		@Override public ParserRule getRule() { return rule; }
		
		//Bool | Number | Void
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Bool
		public RuleCall getBoolParserRuleCall_0() { return cBoolParserRuleCall_0; }
		
		//Number
		public RuleCall getNumberParserRuleCall_1() { return cNumberParserRuleCall_1; }
		
		//Void
		public RuleCall getVoidParserRuleCall_2() { return cVoidParserRuleCall_2; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFuncCallParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVarAssignParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVarDeclParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMovementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cClockParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cControlStructure_ImplParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cLoopParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cConditionalParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cSetSpeedParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Statement returns Statement:
		//    FuncCall | VarAssign | VarDecl | Movement | Clock | ControlStructure_Impl | Loop | Conditional | SetSpeed;
		@Override public ParserRule getRule() { return rule; }
		
		//FuncCall | VarAssign | VarDecl | Movement | Clock | ControlStructure_Impl | Loop | Conditional | SetSpeed
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FuncCall
		public RuleCall getFuncCallParserRuleCall_0() { return cFuncCallParserRuleCall_0; }
		
		//VarAssign
		public RuleCall getVarAssignParserRuleCall_1() { return cVarAssignParserRuleCall_1; }
		
		//VarDecl
		public RuleCall getVarDeclParserRuleCall_2() { return cVarDeclParserRuleCall_2; }
		
		//Movement
		public RuleCall getMovementParserRuleCall_3() { return cMovementParserRuleCall_3; }
		
		//Clock
		public RuleCall getClockParserRuleCall_4() { return cClockParserRuleCall_4; }
		
		//ControlStructure_Impl
		public RuleCall getControlStructure_ImplParserRuleCall_5() { return cControlStructure_ImplParserRuleCall_5; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_6() { return cLoopParserRuleCall_6; }
		
		//Conditional
		public RuleCall getConditionalParserRuleCall_7() { return cConditionalParserRuleCall_7; }
		
		//SetSpeed
		public RuleCall getSetSpeedParserRuleCall_8() { return cSetSpeedParserRuleCall_8; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFuncCallParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVariableRefParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBoolLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNumLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cBoolUnaryOperationParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cNumUnaryOperationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cBoolBinaryOperationParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cNumBinaryOperationParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cSensorAccessParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Expression returns Expression:
		//    FuncCall | VariableRef | BoolLiteral | NumLiteral | BoolUnaryOperation | NumUnaryOperation | BoolBinaryOperation | NumBinaryOperation | SensorAccess;
		@Override public ParserRule getRule() { return rule; }
		
		//FuncCall | VariableRef | BoolLiteral | NumLiteral | BoolUnaryOperation | NumUnaryOperation | BoolBinaryOperation | NumBinaryOperation | SensorAccess
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FuncCall
		public RuleCall getFuncCallParserRuleCall_0() { return cFuncCallParserRuleCall_0; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_1() { return cVariableRefParserRuleCall_1; }
		
		//BoolLiteral
		public RuleCall getBoolLiteralParserRuleCall_2() { return cBoolLiteralParserRuleCall_2; }
		
		//NumLiteral
		public RuleCall getNumLiteralParserRuleCall_3() { return cNumLiteralParserRuleCall_3; }
		
		//BoolUnaryOperation
		public RuleCall getBoolUnaryOperationParserRuleCall_4() { return cBoolUnaryOperationParserRuleCall_4; }
		
		//NumUnaryOperation
		public RuleCall getNumUnaryOperationParserRuleCall_5() { return cNumUnaryOperationParserRuleCall_5; }
		
		//BoolBinaryOperation
		public RuleCall getBoolBinaryOperationParserRuleCall_6() { return cBoolBinaryOperationParserRuleCall_6; }
		
		//NumBinaryOperation
		public RuleCall getNumBinaryOperationParserRuleCall_7() { return cNumBinaryOperationParserRuleCall_7; }
		
		//SensorAccess
		public RuleCall getSensorAccessParserRuleCall_8() { return cSensorAccessParserRuleCall_8; }
	}
	public class TypeVarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TypeVar");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBoolParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNumberParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//TypeVar returns TypeVar:
		//    Bool | Number;
		@Override public ParserRule getRule() { return rule; }
		
		//Bool | Number
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Bool
		public RuleCall getBoolParserRuleCall_0() { return cBoolParserRuleCall_0; }
		
		//Number
		public RuleCall getNumberParserRuleCall_1() { return cNumberParserRuleCall_1; }
	}
	public class FuncDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FuncDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFuncDeclKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cStatementlistKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementlistAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementlistStatementListParserRuleCall_6_0 = (RuleCall)cStatementlistAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//FuncDecl returns FuncDecl:
		//    'FuncDecl'
		//    name=EString
		//    '{'
		//        'type' type=Type
		//        'statementlist' statementlist=StatementList
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'FuncDecl'
		//name=EString
		//'{'
		//    'type' type=Type
		//    'statementlist' statementlist=StatementList
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'FuncDecl'
		public Keyword getFuncDeclKeyword_0() { return cFuncDeclKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=Type
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_4_0() { return cTypeTypeParserRuleCall_4_0; }
		
		//'statementlist'
		public Keyword getStatementlistKeyword_5() { return cStatementlistKeyword_5; }
		
		//statementlist=StatementList
		public Assignment getStatementlistAssignment_6() { return cStatementlistAssignment_6; }
		
		//StatementList
		public RuleCall getStatementlistStatementListParserRuleCall_6_0() { return cStatementlistStatementListParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class StatementListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.StatementList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStatementListAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStatementListKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStateKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cStateAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStateStatementParserRuleCall_3_2_0 = (RuleCall)cStateAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cStateAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cStateStatementParserRuleCall_3_3_1_0 = (RuleCall)cStateAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StatementList returns StatementList:
		//    {StatementList}
		//    'StatementList'
		//    '{'
		//        ('state' '{' state+=Statement ( "," state+=Statement)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{StatementList}
		//'StatementList'
		//'{'
		//    ('state' '{' state+=Statement ( "," state+=Statement)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{StatementList}
		public Action getStatementListAction_0() { return cStatementListAction_0; }
		
		//'StatementList'
		public Keyword getStatementListKeyword_1() { return cStatementListKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('state' '{' state+=Statement ( "," state+=Statement)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'state'
		public Keyword getStateKeyword_3_0() { return cStateKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//state+=Statement
		public Assignment getStateAssignment_3_2() { return cStateAssignment_3_2; }
		
		//Statement
		public RuleCall getStateStatementParserRuleCall_3_2_0() { return cStateStatementParserRuleCall_3_2_0; }
		
		//( "," state+=Statement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//state+=Statement
		public Assignment getStateAssignment_3_3_1() { return cStateAssignment_3_3_1; }
		
		//Statement
		public RuleCall getStateStatementParserRuleCall_3_3_1_0() { return cStateStatementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Bool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Bool returns Bool:
		//    {Bool}
		//    'Bool'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Bool}
		//'Bool'
		public Group getGroup() { return cGroup; }
		
		//{Bool}
		public Action getBoolAction_0() { return cBoolAction_0; }
		
		//'Bool'
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
	}
	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Number");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNumberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUnitKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUnitAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cUnitUnitEnumRuleCall_3_1_0 = (RuleCall)cUnitAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Number returns Number:
		//    {Number}
		//    'Number'
		//    '{'
		//        ('unit' unit=Unit)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Number}
		//'Number'
		//'{'
		//    ('unit' unit=Unit)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Number}
		public Action getNumberAction_0() { return cNumberAction_0; }
		
		//'Number'
		public Keyword getNumberKeyword_1() { return cNumberKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('unit' unit=Unit)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'unit'
		public Keyword getUnitKeyword_3_0() { return cUnitKeyword_3_0; }
		
		//unit=Unit
		public Assignment getUnitAssignment_3_1() { return cUnitAssignment_3_1; }
		
		//Unit
		public RuleCall getUnitUnitEnumRuleCall_3_1_0() { return cUnitUnitEnumRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class VoidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Void");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVoidAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVoidKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Void returns Void:
		//    {Void}
		//    'Void'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Void}
		//'Void'
		public Group getGroup() { return cGroup; }
		
		//{Void}
		public Action getVoidAction_0() { return cVoidAction_0; }
		
		//'Void'
		public Keyword getVoidKeyword_1() { return cVoidKeyword_1; }
	}
	public class FuncCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FuncCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFuncCallAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFuncCallKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFuncdeclKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFuncdeclAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFuncdeclFuncDeclCrossReference_3_1_0 = (CrossReference)cFuncdeclAssignment_3_1.eContents().get(0);
		private final RuleCall cFuncdeclFuncDeclEStringParserRuleCall_3_1_0_1 = (RuleCall)cFuncdeclFuncDeclCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FuncCall returns FuncCall:
		//    {FuncCall}
		//    'FuncCall'
		//    '{'
		//        ('funcdecl' funcdecl=[FuncDecl|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FuncCall}
		//'FuncCall'
		//'{'
		//    ('funcdecl' funcdecl=[FuncDecl|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{FuncCall}
		public Action getFuncCallAction_0() { return cFuncCallAction_0; }
		
		//'FuncCall'
		public Keyword getFuncCallKeyword_1() { return cFuncCallKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('funcdecl' funcdecl=[FuncDecl|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'funcdecl'
		public Keyword getFuncdeclKeyword_3_0() { return cFuncdeclKeyword_3_0; }
		
		//funcdecl=[FuncDecl|EString]
		public Assignment getFuncdeclAssignment_3_1() { return cFuncdeclAssignment_3_1; }
		
		//[FuncDecl|EString]
		public CrossReference getFuncdeclFuncDeclCrossReference_3_1_0() { return cFuncdeclFuncDeclCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFuncdeclFuncDeclEStringParserRuleCall_3_1_0_1() { return cFuncdeclFuncDeclEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class VarAssignElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.VarAssign");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarAssignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVardeclKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cVardeclAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cVardeclVarDeclCrossReference_2_1_0 = (CrossReference)cVardeclAssignment_2_1.eContents().get(0);
		private final RuleCall cVardeclVarDeclEStringParserRuleCall_2_1_0_1 = (RuleCall)cVardeclVarDeclCrossReference_2_1_0.eContents().get(1);
		private final Keyword cExpressionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpressionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpressionExpressionParserRuleCall_4_0 = (RuleCall)cExpressionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//VarAssign returns VarAssign:
		//    'VarAssign'
		//    '{'
		//        ('vardecl' vardecl=[VarDecl|EString])?
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'VarAssign'
		//'{'
		//    ('vardecl' vardecl=[VarDecl|EString])?
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'VarAssign'
		public Keyword getVarAssignKeyword_0() { return cVarAssignKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('vardecl' vardecl=[VarDecl|EString])?
		public Group getGroup_2() { return cGroup_2; }
		
		//'vardecl'
		public Keyword getVardeclKeyword_2_0() { return cVardeclKeyword_2_0; }
		
		//vardecl=[VarDecl|EString]
		public Assignment getVardeclAssignment_2_1() { return cVardeclAssignment_2_1; }
		
		//[VarDecl|EString]
		public CrossReference getVardeclVarDeclCrossReference_2_1_0() { return cVardeclVarDeclCrossReference_2_1_0; }
		
		//EString
		public RuleCall getVardeclVarDeclEStringParserRuleCall_2_1_0_1() { return cVardeclVarDeclEStringParserRuleCall_2_1_0_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_3() { return cExpressionKeyword_3; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_4() { return cExpressionAssignment_4; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_4_0() { return cExpressionExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class VarDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.VarDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarDeclKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeVarParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExpressionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cExpressionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_5_1_0 = (RuleCall)cExpressionAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VarDecl returns VarDecl:
		//    'VarDecl'
		//    name=EString
		//    '{'
		//        'type' type=TypeVar
		//        ('expression' expression=Expression)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'VarDecl'
		//name=EString
		//'{'
		//    'type' type=TypeVar
		//    ('expression' expression=Expression)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'VarDecl'
		public Keyword getVarDeclKeyword_0() { return cVarDeclKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=TypeVar
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//TypeVar
		public RuleCall getTypeTypeVarParserRuleCall_4_0() { return cTypeTypeVarParserRuleCall_4_0; }
		
		//('expression' expression=Expression)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'expression'
		public Keyword getExpressionKeyword_5_0() { return cExpressionKeyword_5_0; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_5_1() { return cExpressionAssignment_5_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_5_1_0() { return cExpressionExpressionParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class MovementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Movement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSideKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSideAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSideDirectionEnumRuleCall_2_1_0 = (RuleCall)cSideAssignment_2_1.eContents().get(0);
		private final Keyword cDistanceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDistanceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDistanceExpressionParserRuleCall_4_0 = (RuleCall)cDistanceAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Movement returns Movement:
		//    'Movement'
		//    '{'
		//        ('side' side=Direction)?
		//        'distance' distance=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Movement'
		//'{'
		//    ('side' side=Direction)?
		//    'distance' distance=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Movement'
		public Keyword getMovementKeyword_0() { return cMovementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('side' side=Direction)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'side'
		public Keyword getSideKeyword_2_0() { return cSideKeyword_2_0; }
		
		//side=Direction
		public Assignment getSideAssignment_2_1() { return cSideAssignment_2_1; }
		
		//Direction
		public RuleCall getSideDirectionEnumRuleCall_2_1_0() { return cSideDirectionEnumRuleCall_2_1_0; }
		
		//'distance'
		public Keyword getDistanceKeyword_3() { return cDistanceKeyword_3; }
		
		//distance=Expression
		public Assignment getDistanceAssignment_4() { return cDistanceAssignment_4; }
		
		//Expression
		public RuleCall getDistanceExpressionParserRuleCall_4_0() { return cDistanceExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ClockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Clock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDistanceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDistanceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDistanceExpressionParserRuleCall_3_0 = (RuleCall)cDistanceAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Clock returns Clock:
		//    'Clock'
		//    '{'
		//        'distance' distance=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Clock'
		//'{'
		//    'distance' distance=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Clock'
		public Keyword getClockKeyword_0() { return cClockKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'distance'
		public Keyword getDistanceKeyword_2() { return cDistanceKeyword_2; }
		
		//distance=Expression
		public Assignment getDistanceAssignment_3() { return cDistanceAssignment_3; }
		
		//Expression
		public RuleCall getDistanceExpressionParserRuleCall_3_0() { return cDistanceExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ControlStructure_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ControlStructure_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cControlStructureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConditionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionExpressionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ControlStructure_Impl returns ControlStructure:
		//    'ControlStructure'
		//    '{'
		//        'condition' condition=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ControlStructure'
		//'{'
		//    'condition' condition=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ControlStructure'
		public Keyword getControlStructureKeyword_0() { return cControlStructureKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'condition'
		public Keyword getConditionKeyword_2() { return cConditionKeyword_2; }
		
		//condition=Expression
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_3_0() { return cConditionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConditionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionExpressionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cBodyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBodyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBodyStatementListParserRuleCall_5_0 = (RuleCall)cBodyAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loop returns Loop:
		//    'Loop'
		//    '{'
		//        'condition' condition=Expression
		//        'body' body=StatementList
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loop'
		//'{'
		//    'condition' condition=Expression
		//    'body' body=StatementList
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'condition'
		public Keyword getConditionKeyword_2() { return cConditionKeyword_2; }
		
		//condition=Expression
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_3_0() { return cConditionExpressionParserRuleCall_3_0; }
		
		//'body'
		public Keyword getBodyKeyword_4() { return cBodyKeyword_4; }
		
		//body=StatementList
		public Assignment getBodyAssignment_5() { return cBodyAssignment_5; }
		
		//StatementList
		public RuleCall getBodyStatementListParserRuleCall_5_0() { return cBodyStatementListParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ConditionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Conditional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConditionalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConditionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionExpressionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cIfBodyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIfBodyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIfBodyStatementListParserRuleCall_5_0 = (RuleCall)cIfBodyAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cElseBodyKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cElseBodyAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cElseBodyStatementListParserRuleCall_6_1_0 = (RuleCall)cElseBodyAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Conditional returns Conditional:
		//    'Conditional'
		//    '{'
		//        'condition' condition=Expression
		//        'ifBody' ifBody=StatementList
		//        ('elseBody' elseBody=StatementList)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Conditional'
		//'{'
		//    'condition' condition=Expression
		//    'ifBody' ifBody=StatementList
		//    ('elseBody' elseBody=StatementList)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Conditional'
		public Keyword getConditionalKeyword_0() { return cConditionalKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'condition'
		public Keyword getConditionKeyword_2() { return cConditionKeyword_2; }
		
		//condition=Expression
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_3_0() { return cConditionExpressionParserRuleCall_3_0; }
		
		//'ifBody'
		public Keyword getIfBodyKeyword_4() { return cIfBodyKeyword_4; }
		
		//ifBody=StatementList
		public Assignment getIfBodyAssignment_5() { return cIfBodyAssignment_5; }
		
		//StatementList
		public RuleCall getIfBodyStatementListParserRuleCall_5_0() { return cIfBodyStatementListParserRuleCall_5_0; }
		
		//('elseBody' elseBody=StatementList)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'elseBody'
		public Keyword getElseBodyKeyword_6_0() { return cElseBodyKeyword_6_0; }
		
		//elseBody=StatementList
		public Assignment getElseBodyAssignment_6_1() { return cElseBodyAssignment_6_1; }
		
		//StatementList
		public RuleCall getElseBodyStatementListParserRuleCall_6_1_0() { return cElseBodyStatementListParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class SetSpeedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SetSpeed");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetSpeedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSpeedKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSpeedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSpeedExpressionParserRuleCall_3_0 = (RuleCall)cSpeedAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SetSpeed returns SetSpeed:
		//    'SetSpeed'
		//    '{'
		//        'speed' speed=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SetSpeed'
		//'{'
		//    'speed' speed=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SetSpeed'
		public Keyword getSetSpeedKeyword_0() { return cSetSpeedKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'speed'
		public Keyword getSpeedKeyword_2() { return cSpeedKeyword_2; }
		
		//speed=Expression
		public Assignment getSpeedAssignment_3() { return cSpeedAssignment_3; }
		
		//Expression
		public RuleCall getSpeedExpressionParserRuleCall_3_0() { return cSpeedExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class VariableRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.VariableRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVariableRefKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVardeclKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cVardeclAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cVardeclVarDeclCrossReference_3_1_0 = (CrossReference)cVardeclAssignment_3_1.eContents().get(0);
		private final RuleCall cVardeclVarDeclEStringParserRuleCall_3_1_0_1 = (RuleCall)cVardeclVarDeclCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//VariableRef returns VariableRef:
		//    {VariableRef}
		//    'VariableRef'
		//    '{'
		//        ('vardecl' vardecl=[VarDecl|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VariableRef}
		//'VariableRef'
		//'{'
		//    ('vardecl' vardecl=[VarDecl|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VariableRef}
		public Action getVariableRefAction_0() { return cVariableRefAction_0; }
		
		//'VariableRef'
		public Keyword getVariableRefKeyword_1() { return cVariableRefKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('vardecl' vardecl=[VarDecl|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'vardecl'
		public Keyword getVardeclKeyword_3_0() { return cVardeclKeyword_3_0; }
		
		//vardecl=[VarDecl|EString]
		public Assignment getVardeclAssignment_3_1() { return cVardeclAssignment_3_1; }
		
		//[VarDecl|EString]
		public CrossReference getVardeclVarDeclCrossReference_3_1_0() { return cVardeclVarDeclCrossReference_3_1_0; }
		
		//EString
		public RuleCall getVardeclVarDeclEStringParserRuleCall_3_1_0_1() { return cVardeclVarDeclEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BoolLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValValKeyword_1_0 = (Keyword)cValAssignment_1.eContents().get(0);
		private final Keyword cBoolLiteralKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//BoolLiteral returns BoolLiteral:
		//    {BoolLiteral}
		//    (val?='val')?
		//    'BoolLiteral'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{BoolLiteral}
		//(val?='val')?
		//'BoolLiteral'
		public Group getGroup() { return cGroup; }
		
		//{BoolLiteral}
		public Action getBoolLiteralAction_0() { return cBoolLiteralAction_0; }
		
		//(val?='val')?
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//'val'
		public Keyword getValValKeyword_1_0() { return cValValKeyword_1_0; }
		
		//'BoolLiteral'
		public Keyword getBoolLiteralKeyword_2() { return cBoolLiteralKeyword_2; }
	}
	public class NumLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NumLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNumLiteralKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValEIntParserRuleCall_3_1_0 = (RuleCall)cValAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//NumLiteral returns NumLiteral:
		//    {NumLiteral}
		//    'NumLiteral'
		//    '{'
		//        ('val' val=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{NumLiteral}
		//'NumLiteral'
		//'{'
		//    ('val' val=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{NumLiteral}
		public Action getNumLiteralAction_0() { return cNumLiteralAction_0; }
		
		//'NumLiteral'
		public Keyword getNumLiteralKeyword_1() { return cNumLiteralKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('val' val=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'val'
		public Keyword getValKeyword_3_0() { return cValKeyword_3_0; }
		
		//val=EInt
		public Assignment getValAssignment_3_1() { return cValAssignment_3_1; }
		
		//EInt
		public RuleCall getValEIntParserRuleCall_3_1_0() { return cValEIntParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BoolUnaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolUnaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoolUnaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypeBoolUOpEnumRuleCall_2_1_0 = (RuleCall)cTypeAssignment_2_1.eContents().get(0);
		private final Keyword cOperandKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOperandAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperandExpressionParserRuleCall_4_0 = (RuleCall)cOperandAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//BoolUnaryOperation returns BoolUnaryOperation:
		//    'BoolUnaryOperation'
		//    '{'
		//        ('type' type=BoolUOp)?
		//        'operand' operand=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'BoolUnaryOperation'
		//'{'
		//    ('type' type=BoolUOp)?
		//    'operand' operand=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'BoolUnaryOperation'
		public Keyword getBoolUnaryOperationKeyword_0() { return cBoolUnaryOperationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('type' type=BoolUOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'type'
		public Keyword getTypeKeyword_2_0() { return cTypeKeyword_2_0; }
		
		//type=BoolUOp
		public Assignment getTypeAssignment_2_1() { return cTypeAssignment_2_1; }
		
		//BoolUOp
		public RuleCall getTypeBoolUOpEnumRuleCall_2_1_0() { return cTypeBoolUOpEnumRuleCall_2_1_0; }
		
		//'operand'
		public Keyword getOperandKeyword_3() { return cOperandKeyword_3; }
		
		//operand=Expression
		public Assignment getOperandAssignment_4() { return cOperandAssignment_4; }
		
		//Expression
		public RuleCall getOperandExpressionParserRuleCall_4_0() { return cOperandExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class NumUnaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NumUnaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumUnaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypeNumUOpEnumRuleCall_2_1_0 = (RuleCall)cTypeAssignment_2_1.eContents().get(0);
		private final Keyword cOperandKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOperandAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperandExpressionParserRuleCall_4_0 = (RuleCall)cOperandAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//NumUnaryOperation returns NumUnaryOperation:
		//    'NumUnaryOperation'
		//    '{'
		//        ('type' type=NumUOp)?
		//        'operand' operand=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'NumUnaryOperation'
		//'{'
		//    ('type' type=NumUOp)?
		//    'operand' operand=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'NumUnaryOperation'
		public Keyword getNumUnaryOperationKeyword_0() { return cNumUnaryOperationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('type' type=NumUOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'type'
		public Keyword getTypeKeyword_2_0() { return cTypeKeyword_2_0; }
		
		//type=NumUOp
		public Assignment getTypeAssignment_2_1() { return cTypeAssignment_2_1; }
		
		//NumUOp
		public RuleCall getTypeNumUOpEnumRuleCall_2_1_0() { return cTypeNumUOpEnumRuleCall_2_1_0; }
		
		//'operand'
		public Keyword getOperandKeyword_3() { return cOperandKeyword_3; }
		
		//operand=Expression
		public Assignment getOperandAssignment_4() { return cOperandAssignment_4; }
		
		//Expression
		public RuleCall getOperandExpressionParserRuleCall_4_0() { return cOperandExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class BoolBinaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolBinaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoolBinaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypeBoolBOpEnumRuleCall_2_1_0 = (RuleCall)cTypeAssignment_2_1.eContents().get(0);
		private final Keyword cOperandsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOperandsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOperandsExpressionParserRuleCall_5_0 = (RuleCall)cOperandsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cOperandsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cOperandsExpressionParserRuleCall_6_1_0 = (RuleCall)cOperandsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//BoolBinaryOperation returns BoolBinaryOperation:
		//    'BoolBinaryOperation'
		//    '{'
		//        ('type' type=BoolBOp)?
		//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'BoolBinaryOperation'
		//'{'
		//    ('type' type=BoolBOp)?
		//    'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'BoolBinaryOperation'
		public Keyword getBoolBinaryOperationKeyword_0() { return cBoolBinaryOperationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('type' type=BoolBOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'type'
		public Keyword getTypeKeyword_2_0() { return cTypeKeyword_2_0; }
		
		//type=BoolBOp
		public Assignment getTypeAssignment_2_1() { return cTypeAssignment_2_1; }
		
		//BoolBOp
		public RuleCall getTypeBoolBOpEnumRuleCall_2_1_0() { return cTypeBoolBOpEnumRuleCall_2_1_0; }
		
		//'operands'
		public Keyword getOperandsKeyword_3() { return cOperandsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_5() { return cOperandsAssignment_5; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_5_0() { return cOperandsExpressionParserRuleCall_5_0; }
		
		//( "," operands+=Expression)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_6_1() { return cOperandsAssignment_6_1; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_6_1_0() { return cOperandsExpressionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class NumBinaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NumBinaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumBinaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypeNumBOpEnumRuleCall_2_1_0 = (RuleCall)cTypeAssignment_2_1.eContents().get(0);
		private final Keyword cOperandsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOperandsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOperandsExpressionParserRuleCall_5_0 = (RuleCall)cOperandsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cOperandsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cOperandsExpressionParserRuleCall_6_1_0 = (RuleCall)cOperandsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//NumBinaryOperation returns NumBinaryOperation:
		//    'NumBinaryOperation'
		//    '{'
		//        ('type' type=NumBOp)?
		//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'NumBinaryOperation'
		//'{'
		//    ('type' type=NumBOp)?
		//    'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'NumBinaryOperation'
		public Keyword getNumBinaryOperationKeyword_0() { return cNumBinaryOperationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('type' type=NumBOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'type'
		public Keyword getTypeKeyword_2_0() { return cTypeKeyword_2_0; }
		
		//type=NumBOp
		public Assignment getTypeAssignment_2_1() { return cTypeAssignment_2_1; }
		
		//NumBOp
		public RuleCall getTypeNumBOpEnumRuleCall_2_1_0() { return cTypeNumBOpEnumRuleCall_2_1_0; }
		
		//'operands'
		public Keyword getOperandsKeyword_3() { return cOperandsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_5() { return cOperandsAssignment_5; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_5_0() { return cOperandsExpressionParserRuleCall_5_0; }
		
		//( "," operands+=Expression)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_6_1() { return cOperandsAssignment_6_1; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_6_1_0() { return cOperandsExpressionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SensorAccessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SensorAccess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorAccessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorAccessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSensorTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSensorTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSensorTypeSensorTypeEnumRuleCall_3_1_0 = (RuleCall)cSensorTypeAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SensorAccess returns SensorAccess:
		//    {SensorAccess}
		//    'SensorAccess'
		//    '{'
		//        ('sensorType' sensorType=SensorType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SensorAccess}
		//'SensorAccess'
		//'{'
		//    ('sensorType' sensorType=SensorType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SensorAccess}
		public Action getSensorAccessAction_0() { return cSensorAccessAction_0; }
		
		//'SensorAccess'
		public Keyword getSensorAccessKeyword_1() { return cSensorAccessKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('sensorType' sensorType=SensorType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'sensorType'
		public Keyword getSensorTypeKeyword_3_0() { return cSensorTypeKeyword_3_0; }
		
		//sensorType=SensorType
		public Assignment getSensorTypeAssignment_3_1() { return cSensorTypeAssignment_3_1; }
		
		//SensorType
		public RuleCall getSensorTypeSensorTypeEnumRuleCall_3_1_0() { return cSensorTypeSensorTypeEnumRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class UnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Unit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCmEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCmCmKeyword_0_0 = (Keyword)cCmEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMmEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMmMmKeyword_1_0 = (Keyword)cMmEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNoneEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNoneNoneKeyword_2_0 = (Keyword)cNoneEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDegEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDegDegKeyword_3_0 = (Keyword)cDegEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRadEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRadRadKeyword_4_0 = (Keyword)cRadEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Unit returns Unit:
		//                cm = 'cm' | mm = 'mm' | none = 'none' | deg = 'deg' | rad = 'rad';
		public EnumRule getRule() { return rule; }
		
		//cm = 'cm' | mm = 'mm' | none = 'none' | deg = 'deg' | rad = 'rad'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//cm = 'cm'
		public EnumLiteralDeclaration getCmEnumLiteralDeclaration_0() { return cCmEnumLiteralDeclaration_0; }
		
		//'cm'
		public Keyword getCmCmKeyword_0_0() { return cCmCmKeyword_0_0; }
		
		//mm = 'mm'
		public EnumLiteralDeclaration getMmEnumLiteralDeclaration_1() { return cMmEnumLiteralDeclaration_1; }
		
		//'mm'
		public Keyword getMmMmKeyword_1_0() { return cMmMmKeyword_1_0; }
		
		//none = 'none'
		public EnumLiteralDeclaration getNoneEnumLiteralDeclaration_2() { return cNoneEnumLiteralDeclaration_2; }
		
		//'none'
		public Keyword getNoneNoneKeyword_2_0() { return cNoneNoneKeyword_2_0; }
		
		//deg = 'deg'
		public EnumLiteralDeclaration getDegEnumLiteralDeclaration_3() { return cDegEnumLiteralDeclaration_3; }
		
		//'deg'
		public Keyword getDegDegKeyword_3_0() { return cDegDegKeyword_3_0; }
		
		//rad = 'rad'
		public EnumLiteralDeclaration getRadEnumLiteralDeclaration_4() { return cRadEnumLiteralDeclaration_4; }
		
		//'rad'
		public Keyword getRadRadKeyword_4_0() { return cRadRadKeyword_4_0; }
	}
	public class BoolUOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolUOp");
		private final EnumLiteralDeclaration cNOTEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cNOTNOTKeyword_0 = (Keyword)cNOTEnumLiteralDeclaration.eContents().get(0);
		
		//enum BoolUOp returns BoolUOp:
		//                NOT = 'NOT';
		public EnumRule getRule() { return rule; }
		
		//NOT = 'NOT'
		public EnumLiteralDeclaration getNOTEnumLiteralDeclaration() { return cNOTEnumLiteralDeclaration; }
		
		//'NOT'
		public Keyword getNOTNOTKeyword_0() { return cNOTNOTKeyword_0; }
	}
	public class NumUOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NumUOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMINUSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMINUSMINUSKeyword_0_0 = (Keyword)cMINUSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPLUSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPLUSPLUSKeyword_1_0 = (Keyword)cPLUSEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum NumUOp returns NumUOp:
		//                MINUS = 'MINUS' | PLUS = 'PLUS';
		public EnumRule getRule() { return rule; }
		
		//MINUS = 'MINUS' | PLUS = 'PLUS'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MINUS = 'MINUS'
		public EnumLiteralDeclaration getMINUSEnumLiteralDeclaration_0() { return cMINUSEnumLiteralDeclaration_0; }
		
		//'MINUS'
		public Keyword getMINUSMINUSKeyword_0_0() { return cMINUSMINUSKeyword_0_0; }
		
		//PLUS = 'PLUS'
		public EnumLiteralDeclaration getPLUSEnumLiteralDeclaration_1() { return cPLUSEnumLiteralDeclaration_1; }
		
		//'PLUS'
		public Keyword getPLUSPLUSKeyword_1_0() { return cPLUSPLUSKeyword_1_0; }
	}
	public class BoolBOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolBOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEQEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEQEQKeyword_0_0 = (Keyword)cEQEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNEQEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNEQNEQKeyword_1_0 = (Keyword)cNEQEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLEQEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLEQLEQKeyword_2_0 = (Keyword)cLEQEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGEQEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGEQGEQKeyword_3_0 = (Keyword)cGEQEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLELEKeyword_4_0 = (Keyword)cLEEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cGREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cGRGRKeyword_5_0 = (Keyword)cGREnumLiteralDeclaration_5.eContents().get(0);
		
		//enum BoolBOp returns BoolBOp:
		//                EQ = 'EQ' | NEQ = 'NEQ' | LEQ = 'LEQ' | GEQ = 'GEQ' | LE = 'LE' | GR = 'GR';
		public EnumRule getRule() { return rule; }
		
		//EQ = 'EQ' | NEQ = 'NEQ' | LEQ = 'LEQ' | GEQ = 'GEQ' | LE = 'LE' | GR = 'GR'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EQ = 'EQ'
		public EnumLiteralDeclaration getEQEnumLiteralDeclaration_0() { return cEQEnumLiteralDeclaration_0; }
		
		//'EQ'
		public Keyword getEQEQKeyword_0_0() { return cEQEQKeyword_0_0; }
		
		//NEQ = 'NEQ'
		public EnumLiteralDeclaration getNEQEnumLiteralDeclaration_1() { return cNEQEnumLiteralDeclaration_1; }
		
		//'NEQ'
		public Keyword getNEQNEQKeyword_1_0() { return cNEQNEQKeyword_1_0; }
		
		//LEQ = 'LEQ'
		public EnumLiteralDeclaration getLEQEnumLiteralDeclaration_2() { return cLEQEnumLiteralDeclaration_2; }
		
		//'LEQ'
		public Keyword getLEQLEQKeyword_2_0() { return cLEQLEQKeyword_2_0; }
		
		//GEQ = 'GEQ'
		public EnumLiteralDeclaration getGEQEnumLiteralDeclaration_3() { return cGEQEnumLiteralDeclaration_3; }
		
		//'GEQ'
		public Keyword getGEQGEQKeyword_3_0() { return cGEQGEQKeyword_3_0; }
		
		//LE = 'LE'
		public EnumLiteralDeclaration getLEEnumLiteralDeclaration_4() { return cLEEnumLiteralDeclaration_4; }
		
		//'LE'
		public Keyword getLELEKeyword_4_0() { return cLELEKeyword_4_0; }
		
		//GR = 'GR'
		public EnumLiteralDeclaration getGREnumLiteralDeclaration_5() { return cGREnumLiteralDeclaration_5; }
		
		//'GR'
		public Keyword getGRGRKeyword_5_0() { return cGRGRKeyword_5_0; }
	}
	public class NumBOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NumBOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMINUSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMINUSMINUSKeyword_0_0 = (Keyword)cMINUSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPLUSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPLUSPLUSKeyword_1_0 = (Keyword)cPLUSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMULTIPLYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMULTIPLYMULTIPLYKeyword_2_0 = (Keyword)cMULTIPLYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDIVIDEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDIVIDEDIVIDEKeyword_3_0 = (Keyword)cDIVIDEEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum NumBOp returns NumBOp:
		//                MINUS = 'MINUS' | PLUS = 'PLUS' | MULTIPLY = 'MULTIPLY' | DIVIDE = 'DIVIDE';
		public EnumRule getRule() { return rule; }
		
		//MINUS = 'MINUS' | PLUS = 'PLUS' | MULTIPLY = 'MULTIPLY' | DIVIDE = 'DIVIDE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MINUS = 'MINUS'
		public EnumLiteralDeclaration getMINUSEnumLiteralDeclaration_0() { return cMINUSEnumLiteralDeclaration_0; }
		
		//'MINUS'
		public Keyword getMINUSMINUSKeyword_0_0() { return cMINUSMINUSKeyword_0_0; }
		
		//PLUS = 'PLUS'
		public EnumLiteralDeclaration getPLUSEnumLiteralDeclaration_1() { return cPLUSEnumLiteralDeclaration_1; }
		
		//'PLUS'
		public Keyword getPLUSPLUSKeyword_1_0() { return cPLUSPLUSKeyword_1_0; }
		
		//MULTIPLY = 'MULTIPLY'
		public EnumLiteralDeclaration getMULTIPLYEnumLiteralDeclaration_2() { return cMULTIPLYEnumLiteralDeclaration_2; }
		
		//'MULTIPLY'
		public Keyword getMULTIPLYMULTIPLYKeyword_2_0() { return cMULTIPLYMULTIPLYKeyword_2_0; }
		
		//DIVIDE = 'DIVIDE'
		public EnumLiteralDeclaration getDIVIDEEnumLiteralDeclaration_3() { return cDIVIDEEnumLiteralDeclaration_3; }
		
		//'DIVIDE'
		public Keyword getDIVIDEDIVIDEKeyword_3_0() { return cDIVIDEDIVIDEKeyword_3_0; }
	}
	public class SensorTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SensorType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDistanceEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDistanceDistanceKeyword_0_0 = (Keyword)cDistanceEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTimeEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTimeTimeKeyword_1_0 = (Keyword)cTimeEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBatteryEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBatteryBatteryKeyword_2_0 = (Keyword)cBatteryEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum SensorType returns SensorType:
		//                Distance = 'Distance' | Time = 'Time' | Battery = 'Battery';
		public EnumRule getRule() { return rule; }
		
		//Distance = 'Distance' | Time = 'Time' | Battery = 'Battery'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Distance = 'Distance'
		public EnumLiteralDeclaration getDistanceEnumLiteralDeclaration_0() { return cDistanceEnumLiteralDeclaration_0; }
		
		//'Distance'
		public Keyword getDistanceDistanceKeyword_0_0() { return cDistanceDistanceKeyword_0_0; }
		
		//Time = 'Time'
		public EnumLiteralDeclaration getTimeEnumLiteralDeclaration_1() { return cTimeEnumLiteralDeclaration_1; }
		
		//'Time'
		public Keyword getTimeTimeKeyword_1_0() { return cTimeTimeKeyword_1_0; }
		
		//Battery = 'Battery'
		public EnumLiteralDeclaration getBatteryEnumLiteralDeclaration_2() { return cBatteryEnumLiteralDeclaration_2; }
		
		//'Battery'
		public Keyword getBatteryBatteryKeyword_2_0() { return cBatteryBatteryKeyword_2_0; }
	}
	public class DirectionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Direction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBackwardEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBackwardBackwardKeyword_0_0 = (Keyword)cBackwardEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cForwardEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cForwardForwardKeyword_1_0 = (Keyword)cForwardEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSideleftEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSideleftSideleftKeyword_2_0 = (Keyword)cSideleftEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSiderightEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSiderightSiderightKeyword_3_0 = (Keyword)cSiderightEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Direction returns Direction:
		//                Backward = 'Backward' | Forward = 'Forward' | Sideleft = 'Sideleft' | Sideright = 'Sideright';
		public EnumRule getRule() { return rule; }
		
		//Backward = 'Backward' | Forward = 'Forward' | Sideleft = 'Sideleft' | Sideright = 'Sideright'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Backward = 'Backward'
		public EnumLiteralDeclaration getBackwardEnumLiteralDeclaration_0() { return cBackwardEnumLiteralDeclaration_0; }
		
		//'Backward'
		public Keyword getBackwardBackwardKeyword_0_0() { return cBackwardBackwardKeyword_0_0; }
		
		//Forward = 'Forward'
		public EnumLiteralDeclaration getForwardEnumLiteralDeclaration_1() { return cForwardEnumLiteralDeclaration_1; }
		
		//'Forward'
		public Keyword getForwardForwardKeyword_1_0() { return cForwardForwardKeyword_1_0; }
		
		//Sideleft = 'Sideleft'
		public EnumLiteralDeclaration getSideleftEnumLiteralDeclaration_2() { return cSideleftEnumLiteralDeclaration_2; }
		
		//'Sideleft'
		public Keyword getSideleftSideleftKeyword_2_0() { return cSideleftSideleftKeyword_2_0; }
		
		//Sideright = 'Sideright'
		public EnumLiteralDeclaration getSiderightEnumLiteralDeclaration_3() { return cSiderightEnumLiteralDeclaration_3; }
		
		//'Sideright'
		public Keyword getSiderightSiderightKeyword_3_0() { return cSiderightSiderightKeyword_3_0; }
	}
	
	private final ProgrammeElements pProgramme;
	private final TypeElements pType;
	private final StatementElements pStatement;
	private final ExpressionElements pExpression;
	private final TypeVarElements pTypeVar;
	private final FuncDeclElements pFuncDecl;
	private final StatementListElements pStatementList;
	private final EStringElements pEString;
	private final BoolElements pBool;
	private final NumberElements pNumber;
	private final VoidElements pVoid;
	private final UnitElements eUnit;
	private final FuncCallElements pFuncCall;
	private final VarAssignElements pVarAssign;
	private final VarDeclElements pVarDecl;
	private final MovementElements pMovement;
	private final ClockElements pClock;
	private final ControlStructure_ImplElements pControlStructure_Impl;
	private final LoopElements pLoop;
	private final ConditionalElements pConditional;
	private final SetSpeedElements pSetSpeed;
	private final VariableRefElements pVariableRef;
	private final BoolLiteralElements pBoolLiteral;
	private final NumLiteralElements pNumLiteral;
	private final BoolUnaryOperationElements pBoolUnaryOperation;
	private final NumUnaryOperationElements pNumUnaryOperation;
	private final BoolBinaryOperationElements pBoolBinaryOperation;
	private final NumBinaryOperationElements pNumBinaryOperation;
	private final SensorAccessElements pSensorAccess;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final BoolUOpElements eBoolUOp;
	private final NumUOpElements eNumUOp;
	private final BoolBOpElements eBoolBOp;
	private final NumBOpElements eNumBOp;
	private final SensorTypeElements eSensorType;
	private final DirectionElements eDirection;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgramme = new ProgrammeElements();
		this.pType = new TypeElements();
		this.pStatement = new StatementElements();
		this.pExpression = new ExpressionElements();
		this.pTypeVar = new TypeVarElements();
		this.pFuncDecl = new FuncDeclElements();
		this.pStatementList = new StatementListElements();
		this.pEString = new EStringElements();
		this.pBool = new BoolElements();
		this.pNumber = new NumberElements();
		this.pVoid = new VoidElements();
		this.eUnit = new UnitElements();
		this.pFuncCall = new FuncCallElements();
		this.pVarAssign = new VarAssignElements();
		this.pVarDecl = new VarDeclElements();
		this.pMovement = new MovementElements();
		this.pClock = new ClockElements();
		this.pControlStructure_Impl = new ControlStructure_ImplElements();
		this.pLoop = new LoopElements();
		this.pConditional = new ConditionalElements();
		this.pSetSpeed = new SetSpeedElements();
		this.pVariableRef = new VariableRefElements();
		this.pBoolLiteral = new BoolLiteralElements();
		this.pNumLiteral = new NumLiteralElements();
		this.pBoolUnaryOperation = new BoolUnaryOperationElements();
		this.pNumUnaryOperation = new NumUnaryOperationElements();
		this.pBoolBinaryOperation = new BoolBinaryOperationElements();
		this.pNumBinaryOperation = new NumBinaryOperationElements();
		this.pSensorAccess = new SensorAccessElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.eBoolUOp = new BoolUOpElements();
		this.eNumUOp = new NumUOpElements();
		this.eBoolBOp = new BoolBOpElements();
		this.eNumBOp = new NumBOpElements();
		this.eSensorType = new SensorTypeElements();
		this.eDirection = new DirectionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programme returns Programme:
	//    {Programme}
	//    'Programme'
	//    '{'
	//        ('funcdecl' '{' funcdecl+=FuncDecl ( "," funcdecl+=FuncDecl)* '}' )?
	//    '}';
	public ProgrammeElements getProgrammeAccess() {
		return pProgramme;
	}
	
	public ParserRule getProgrammeRule() {
		return getProgrammeAccess().getRule();
	}
	
	//Type returns Type:
	//    Bool | Number | Void;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Statement returns Statement:
	//    FuncCall | VarAssign | VarDecl | Movement | Clock | ControlStructure_Impl | Loop | Conditional | SetSpeed;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Expression returns Expression:
	//    FuncCall | VariableRef | BoolLiteral | NumLiteral | BoolUnaryOperation | NumUnaryOperation | BoolBinaryOperation | NumBinaryOperation | SensorAccess;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//TypeVar returns TypeVar:
	//    Bool | Number;
	public TypeVarElements getTypeVarAccess() {
		return pTypeVar;
	}
	
	public ParserRule getTypeVarRule() {
		return getTypeVarAccess().getRule();
	}
	
	//FuncDecl returns FuncDecl:
	//    'FuncDecl'
	//    name=EString
	//    '{'
	//        'type' type=Type
	//        'statementlist' statementlist=StatementList
	//    '}';
	public FuncDeclElements getFuncDeclAccess() {
		return pFuncDecl;
	}
	
	public ParserRule getFuncDeclRule() {
		return getFuncDeclAccess().getRule();
	}
	
	//StatementList returns StatementList:
	//    {StatementList}
	//    'StatementList'
	//    '{'
	//        ('state' '{' state+=Statement ( "," state+=Statement)* '}' )?
	//    '}';
	public StatementListElements getStatementListAccess() {
		return pStatementList;
	}
	
	public ParserRule getStatementListRule() {
		return getStatementListAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Bool returns Bool:
	//    {Bool}
	//    'Bool'
	//    ;
	public BoolElements getBoolAccess() {
		return pBool;
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//Number returns Number:
	//    {Number}
	//    'Number'
	//    '{'
	//        ('unit' unit=Unit)?
	//    '}';
	public NumberElements getNumberAccess() {
		return pNumber;
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}
	
	//Void returns Void:
	//    {Void}
	//    'Void'
	//    ;
	public VoidElements getVoidAccess() {
		return pVoid;
	}
	
	public ParserRule getVoidRule() {
		return getVoidAccess().getRule();
	}
	
	//enum Unit returns Unit:
	//                cm = 'cm' | mm = 'mm' | none = 'none' | deg = 'deg' | rad = 'rad';
	public UnitElements getUnitAccess() {
		return eUnit;
	}
	
	public EnumRule getUnitRule() {
		return getUnitAccess().getRule();
	}
	
	//FuncCall returns FuncCall:
	//    {FuncCall}
	//    'FuncCall'
	//    '{'
	//        ('funcdecl' funcdecl=[FuncDecl|EString])?
	//    '}';
	public FuncCallElements getFuncCallAccess() {
		return pFuncCall;
	}
	
	public ParserRule getFuncCallRule() {
		return getFuncCallAccess().getRule();
	}
	
	//VarAssign returns VarAssign:
	//    'VarAssign'
	//    '{'
	//        ('vardecl' vardecl=[VarDecl|EString])?
	//        'expression' expression=Expression
	//    '}';
	public VarAssignElements getVarAssignAccess() {
		return pVarAssign;
	}
	
	public ParserRule getVarAssignRule() {
		return getVarAssignAccess().getRule();
	}
	
	//VarDecl returns VarDecl:
	//    'VarDecl'
	//    name=EString
	//    '{'
	//        'type' type=TypeVar
	//        ('expression' expression=Expression)?
	//    '}';
	public VarDeclElements getVarDeclAccess() {
		return pVarDecl;
	}
	
	public ParserRule getVarDeclRule() {
		return getVarDeclAccess().getRule();
	}
	
	//Movement returns Movement:
	//    'Movement'
	//    '{'
	//        ('side' side=Direction)?
	//        'distance' distance=Expression
	//    '}';
	public MovementElements getMovementAccess() {
		return pMovement;
	}
	
	public ParserRule getMovementRule() {
		return getMovementAccess().getRule();
	}
	
	//Clock returns Clock:
	//    'Clock'
	//    '{'
	//        'distance' distance=Expression
	//    '}';
	public ClockElements getClockAccess() {
		return pClock;
	}
	
	public ParserRule getClockRule() {
		return getClockAccess().getRule();
	}
	
	//ControlStructure_Impl returns ControlStructure:
	//    'ControlStructure'
	//    '{'
	//        'condition' condition=Expression
	//    '}';
	public ControlStructure_ImplElements getControlStructure_ImplAccess() {
		return pControlStructure_Impl;
	}
	
	public ParserRule getControlStructure_ImplRule() {
		return getControlStructure_ImplAccess().getRule();
	}
	
	//Loop returns Loop:
	//    'Loop'
	//    '{'
	//        'condition' condition=Expression
	//        'body' body=StatementList
	//    '}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//Conditional returns Conditional:
	//    'Conditional'
	//    '{'
	//        'condition' condition=Expression
	//        'ifBody' ifBody=StatementList
	//        ('elseBody' elseBody=StatementList)?
	//    '}';
	public ConditionalElements getConditionalAccess() {
		return pConditional;
	}
	
	public ParserRule getConditionalRule() {
		return getConditionalAccess().getRule();
	}
	
	//SetSpeed returns SetSpeed:
	//    'SetSpeed'
	//    '{'
	//        'speed' speed=Expression
	//    '}';
	public SetSpeedElements getSetSpeedAccess() {
		return pSetSpeed;
	}
	
	public ParserRule getSetSpeedRule() {
		return getSetSpeedAccess().getRule();
	}
	
	//VariableRef returns VariableRef:
	//    {VariableRef}
	//    'VariableRef'
	//    '{'
	//        ('vardecl' vardecl=[VarDecl|EString])?
	//    '}';
	public VariableRefElements getVariableRefAccess() {
		return pVariableRef;
	}
	
	public ParserRule getVariableRefRule() {
		return getVariableRefAccess().getRule();
	}
	
	//BoolLiteral returns BoolLiteral:
	//    {BoolLiteral}
	//    (val?='val')?
	//    'BoolLiteral'
	//    ;
	public BoolLiteralElements getBoolLiteralAccess() {
		return pBoolLiteral;
	}
	
	public ParserRule getBoolLiteralRule() {
		return getBoolLiteralAccess().getRule();
	}
	
	//NumLiteral returns NumLiteral:
	//    {NumLiteral}
	//    'NumLiteral'
	//    '{'
	//        ('val' val=EInt)?
	//    '}';
	public NumLiteralElements getNumLiteralAccess() {
		return pNumLiteral;
	}
	
	public ParserRule getNumLiteralRule() {
		return getNumLiteralAccess().getRule();
	}
	
	//BoolUnaryOperation returns BoolUnaryOperation:
	//    'BoolUnaryOperation'
	//    '{'
	//        ('type' type=BoolUOp)?
	//        'operand' operand=Expression
	//    '}';
	public BoolUnaryOperationElements getBoolUnaryOperationAccess() {
		return pBoolUnaryOperation;
	}
	
	public ParserRule getBoolUnaryOperationRule() {
		return getBoolUnaryOperationAccess().getRule();
	}
	
	//NumUnaryOperation returns NumUnaryOperation:
	//    'NumUnaryOperation'
	//    '{'
	//        ('type' type=NumUOp)?
	//        'operand' operand=Expression
	//    '}';
	public NumUnaryOperationElements getNumUnaryOperationAccess() {
		return pNumUnaryOperation;
	}
	
	public ParserRule getNumUnaryOperationRule() {
		return getNumUnaryOperationAccess().getRule();
	}
	
	//BoolBinaryOperation returns BoolBinaryOperation:
	//    'BoolBinaryOperation'
	//    '{'
	//        ('type' type=BoolBOp)?
	//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
	//    '}';
	public BoolBinaryOperationElements getBoolBinaryOperationAccess() {
		return pBoolBinaryOperation;
	}
	
	public ParserRule getBoolBinaryOperationRule() {
		return getBoolBinaryOperationAccess().getRule();
	}
	
	//NumBinaryOperation returns NumBinaryOperation:
	//    'NumBinaryOperation'
	//    '{'
	//        ('type' type=NumBOp)?
	//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
	//    '}';
	public NumBinaryOperationElements getNumBinaryOperationAccess() {
		return pNumBinaryOperation;
	}
	
	public ParserRule getNumBinaryOperationRule() {
		return getNumBinaryOperationAccess().getRule();
	}
	
	//SensorAccess returns SensorAccess:
	//    {SensorAccess}
	//    'SensorAccess'
	//    '{'
	//        ('sensorType' sensorType=SensorType)?
	//    '}';
	public SensorAccessElements getSensorAccessAccess() {
		return pSensorAccess;
	}
	
	public ParserRule getSensorAccessRule() {
		return getSensorAccessAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum BoolUOp returns BoolUOp:
	//                NOT = 'NOT';
	public BoolUOpElements getBoolUOpAccess() {
		return eBoolUOp;
	}
	
	public EnumRule getBoolUOpRule() {
		return getBoolUOpAccess().getRule();
	}
	
	//enum NumUOp returns NumUOp:
	//                MINUS = 'MINUS' | PLUS = 'PLUS';
	public NumUOpElements getNumUOpAccess() {
		return eNumUOp;
	}
	
	public EnumRule getNumUOpRule() {
		return getNumUOpAccess().getRule();
	}
	
	//enum BoolBOp returns BoolBOp:
	//                EQ = 'EQ' | NEQ = 'NEQ' | LEQ = 'LEQ' | GEQ = 'GEQ' | LE = 'LE' | GR = 'GR';
	public BoolBOpElements getBoolBOpAccess() {
		return eBoolBOp;
	}
	
	public EnumRule getBoolBOpRule() {
		return getBoolBOpAccess().getRule();
	}
	
	//enum NumBOp returns NumBOp:
	//                MINUS = 'MINUS' | PLUS = 'PLUS' | MULTIPLY = 'MULTIPLY' | DIVIDE = 'DIVIDE';
	public NumBOpElements getNumBOpAccess() {
		return eNumBOp;
	}
	
	public EnumRule getNumBOpRule() {
		return getNumBOpAccess().getRule();
	}
	
	//enum SensorType returns SensorType:
	//                Distance = 'Distance' | Time = 'Time' | Battery = 'Battery';
	public SensorTypeElements getSensorTypeAccess() {
		return eSensorType;
	}
	
	public EnumRule getSensorTypeRule() {
		return getSensorTypeAccess().getRule();
	}
	
	//enum Direction returns Direction:
	//                Backward = 'Backward' | Forward = 'Forward' | Sideleft = 'Sideleft' | Sideright = 'Sideright';
	public DirectionElements getDirectionAccess() {
		return eDirection;
	}
	
	public EnumRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
